spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gbi
    username: root
    password: jj789632145
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jiji.jsoup.entity